### ISSUE TITLE
'Get Services' Icon Link height is smaller than other two boxes; hover over is smaller as a result

### ISSUE THREAD

**Issue by josephdt12** [philipwalton/solved-by-flexbox#101]
Resolves once the user logs in due to the 4th bike making the boxes all be the same size. Issue only occurs if not logged in.

**Comment by philipwalton** [comment]
There is no log-in on the site, I'm assuming you're referring to something else?

**Comment by josephdt12** [comment]
Wow, I just found this. Yes, definitely the wrong repo.
