### ISSUE TITLE
guide ?

### ISSUE THREAD

**Issue by CyrusZei** [philipwalton/solved-by-flexbox#104]
I dont see any Template or "get started" code for new users ?

I mean is it 

Grid
  Grid--cell
    Grid--1of2

or is it
Grid
  Grid--1of2
    Grid--cell

You understand that people get that wrong right ?

And if you are doing a demo a good thing is to use the grid css that you made in your own stuffs ;)

**Comment by the94air** [comment]
:+1:

**Comment by CyrusZei** [comment]
If you want I can do the doc's for you ? I made a flexbox grid that I am not 100% done with.

[https://github.com/CyrusZei/blocks](url)
