### ISSUE TITLE
Sticky footer and sidebar

### ISSUE THREAD

**Issue by dasa123** [philipwalton/solved-by-flexbox#108]
Hi *,

I am using the sidebar of Semantic UI and your sticky footer solution. It's working well so far except for IE11.

The problem lies with the sidebar requiring its content to be replaced outside of the header, main, footer tags. I have already described the problem in the Semantic UI ticket tracker. As I don't know from which angle to solve this problem (patch sidebar or patch sticky footer) I open this ticket.

The ticket in the Semantic UI ticket tracker is here:
https://github.com/Semantic-Org/Semantic-UI/issues/5955

Best regards,
dasa123

**Comment by dasa123** [comment]
I think I got it working:
https://github.com/Semantic-Org/Semantic-UI/issues/5955#issuecomment-344863757

**Comment by dannyk08** [comment]
I'm glad you got it resolved. And apologies for the late response 😬
