### ISSUE TITLE
Sticky footer corrupts printing in Firefox and probably IE

### ISSUE THREAD

**Issue by michelgotta** [philipwalton/solved-by-flexbox#109]
The ```body { display: flex; }``` results in unwanted printing problems. Only the first page is printed. Everything else is just cut off. Please add some print-specific ```display: block``` to your example.

**Comment by philipwalton** [comment]
Thanks, but that sounds like a generic issue with flexbox and printing and not something this site needs to warn about. It's just a demo explaining how to achieve an affect, not a comprehensive guide to using flexbox in all possible contexts.
