### ISSUE TITLE
Very small nitpick with Sticky Footer

### ISSUE THREAD

**Issue by petty** [philipwalton/solved-by-flexbox#119]
... the name Sticky Footer implied to me that the footer would have the property `position` set to `sticky` (e.g.  `position: sticky`).  I absolutely get the problem solved in the example & it is a completely valid, useful problem; but I think the name should be something more like "Ensure Footer stays at the bottom of the Viewport for minimal content."  Or something like that.

**Comment by philipwalton** [comment]
The term "sticky footer" existed long before I made this site (in 2013) and was a commonly referenced design problem (hence how Flexbox "solved" it).

If you do a  [Google search for "sticky footer"](https://www.google.com/search?q=sticky+footer&tbs=cdr%3A1%2Ccd_min%3A1%2F1%2F2001%2Ccd_max%3A9%2F1%2F2013) (limiting your results to earlier than September 2013), you'll see lots of results.

The CSS `position:sticky` feature came much later.
