### ISSUE TITLE
Sticky footer doesn't work at all in IE11 and not well in Chrome

### ISSUE THREAD

**Issue by borekb** [philipwalton/solved-by-flexbox#28]
Took the demo code here: http://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/ and observed a couple of things:
- The footer is not pushed down in IE11 and overlays the body section
- In Chrome and Firefox, scrollbar is drawn unnecessarily (part of the footer is under the fold)

**Comment by Alex-Golovin** [comment]
Working example:
http://jsbin.com/ERELezu/24/edit?html,css,output
