### ISSUE TITLE
Sticky footer overlaps disqus comments.

### ISSUE THREAD

**Issue by nmabhinandan** [philipwalton/solved-by-flexbox#43]
I tried to use your sticky footer method and it works like a charm. But if the page has disqus comments on it, it loads after the page load (using js) and the footer overlaps the comments instead of pushing downwards.

**Comment by KenPowers** [comment]
I use the sticky footer on my site with disqus comments and everything works fine.

http://www.kenpowers.net/blog/testing-in-browsers-and-node/

**Comment by philipwalton** [comment]
This sounds like a browser or implementation bug to me. There's nothing about flexbox that shouldn't work just fine with disqus comments or iframes in general.
