### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by kostonstyle** [philipwalton/solved-by-flexbox#46]
Hi 
How can I use this framework, or how to use it?

Thanks

**Comment by philipwalton** [comment]
As I [state on the home page](https://github.com/philipwalton/solved-by-flexbox/blob/cbc3e73f76d9c11e24e2f7880c5d6223e148e95f/index.html#L10), this is not a framework. It's a demo site.

**Comment by kostonstyle** [comment]
ok thx.
