### ISSUE TITLE
Failed at start script NODE_ENV=dev gulp serve

### ISSUE THREAD

**Issue by covijt** [philipwalton/solved-by-flexbox#53]
Greetings,
weather using Nodejs in Visual Studio 2013 pro or trough Node command line,
there is a failure to start. As per the attached npm-debug.log, the problem doe's not seem to stem for npm but most likely with solved-by-flexbox package.

Kinds regards,
Denis

![startfailure](https://cloud.githubusercontent.com/assets/6185999/7840548/e68dfc3e-0465-11e5-8dd3-73ba2350fa7d.PNG)

**Comment by talamus** [comment]
The example software provided does not work with Windows.
It works nicely with Mac or Linux.

**Comment by covijt** [comment]
Greetings,
your swiftness is much appreciated.

Kind regards,
Denis

**Comment by philipwalton** [comment]
Fixed via a8177b96988a2be2ee257252a3a7f606fbf8046f.
