### ISSUE TITLE
Sticky footer not working

### ISSUE THREAD

**Issue by spicydonuts** [philipwalton/solved-by-flexbox#56]
Tried in Safari and Chrome

**Comment by philipwalton** [comment]
It's working fine for me in both Safari and Chrome. Can you be more specific?

**Comment by spicydonuts** [comment]
Here are some screenshots.  Maybe I'm misunderstanding.. shouldn't the footer be stuck to the bottom and visible no matter where it's scrolled to?

![sticky-top](https://cloud.githubusercontent.com/assets/715921/8265534/31ec208c-16ba-11e5-970f-b43099b90986.png)

![sticky-mid](https://cloud.githubusercontent.com/assets/715921/8265503/280ee88e-16b9-11e5-93cc-ddb1a5061b9d.png)

![sticky-bot](https://cloud.githubusercontent.com/assets/715921/8265532/202f83f2-16ba-11e5-96ef-f59eac3c7fad.png)

**Comment by philipwalton** [comment]
No, a sticky footer is one that sticks to the bottom of the screen on pages without much content, but scrolls with the content on longer pages.

**Comment by spicydonuts** [comment]
Oh, got it.  Sorry.

**Comment by philipwalton** [comment]
No worries.
