### ISSUE TITLE
Flex grid columns not rendering on mobile device (tested on iphone)

### ISSUE THREAD

**Issue by amazingBastard** [philipwalton/solved-by-flexbox#57]
Hey there,

I've been having some issues with my flexgrid columns not rendering properly when viewing from my iphone. I set up a quick demo of it here using meteor: http://flexgridtest.meteor.com

Here's the link to the repo: https://github.com/amazingBastard/flexgrid-mobile-test

I used the grid.css from this repo and the grid I made based on your code. Not sure why it's reacting this way. Checked the link on my phone with chrome and safari and the grid isn't rendering as it's supposed to. It does work when I'm looking at the site with my laptop and resizing the browser window.

Any ideas? Thanks for the help!

**Comment by ElijahFowler** [comment]
Looking at your repo, flexgrid.css only has the cutting edge flexbox properties, and iOS uses an older spec.

If you copy the CSS from flexgrid.css and past it into the appropriate field [here (Autoprefixer online)](http://autoprefixer.github.io/) you'll see that a lot of properties are missing.

You can copy/paste what Autoprefixer online outputs and save it in your file, and then you should be good.

I would suggest that you read up in the spec a little, here are a few articles you might find helpful:

* [A Complete Guide to Flexbox [CSS-Tricks]](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)
* [A Visual Guide to CSS3 Flexbox Properties [scotch.io]](https://scotch.io/tutorials/a-visual-guide-to-css3-flexbox-properties)
* [Can I Use - Flexbox](http://caniuse.com/#feat=flexbox) (Browser support, notes on which browsers use old syntax or what bugs they might have)

Hope this helps,
-Elijah

**Comment by philipwalton** [comment]
What @ElijahFowler said. I'd recommend adding autoprefixer to your build step, that way you don't even have to think about this stuff (most of the time).

**Comment by amazingBastard** [comment]
Thanks a lot guys, this helps a lot.
