### ISSUE TITLE
broken br

### ISSUE THREAD

**Issue by aolko** [philipwalton/solved-by-flexbox#60]
i was using flex-centering and discovered that my `<br>` is broken, wtf?
![code](http://i.imgur.com/gtbkj0t.png)
![mrkup](http://i.imgur.com/ySaWnVF.png)
![render](http://i.imgur.com/k7WD7nT.png)
Notice the 123 part
(when i untick `display:flex` in chrome it works fine and also breaks the alignment)

**Comment by Hiswe** [comment]
It's logical.
A flexbox change the positioning of it's direct children.
So if you want to align your items you can:

- make a wrapper division
- change the `flex-direction` to `column`.

more details here: https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by philipwalton** [comment]
Closing as this has nothing to do with this repo and more to do with flexbox itself. If you have issues with flexbox, you should bring them up on the [www-style](https://lists.w3.org/Archives/Public/www-style/) mailing list.
