### ISSUE TITLE
Sticky Footer

### ISSUE THREAD

**Issue by Undistraction** [philipwalton/solved-by-flexbox#62]
In your sticky footer example you show the following selector:

```
.Site {
  display: flex;
  min-height: 100vh;
  flex-direction: column;
}
```

However you page actually uses `height: 100%` . The styles you show (`min-height: 100vh`) won't work in IE11.

**Comment by philipwalton** [comment]
I address this on the home page in the "About the code" section:

> All of the code samples on this site show how to solve a particular design problem with Flexbox. They show just the code that's needed to make the demos work in a spec-compliant browser. Some browsers do not fully comply with the latest version of the spec, so sadly, a few workarounds were necessary.

> Workarounds for non-compliant browsers are not shown in the code samples, but if you're curious about those implementation details, you can check out the source files. Each demo links to its source, and all browser-specific workarounds are well-documented, so don't be afraid to take a look.

**Comment by Undistraction** [comment]
I think you misunderstood. I'm not complaining that the example doesn't work in IE, but that the markup you actually use is different from the markup you say you are using so that it looks like it *does* work in IE. 

In your own words:

> Workarounds for non-compliant browsers are not shown in the code samples

But in reality the whole sticky footer example is itself a workaround because it uses `height` rather than `min-height` that you say you are using. It would make more sense if you used `min-height` for the example as you do in the markup shown on the page, and allow it to fail in IE.
