### ISSUE TITLE
Sticky Footer doesn't stick in Google Chrome Version 44.0.2403.157 m

### ISSUE THREAD

**Issue by greyhwndz** [philipwalton/solved-by-flexbox#63]

**Comment by philipwalton** [comment]
Can you be more specific -- maybe include a screen shot? I'm using Chrome 44.0.2403.157 on OS X and it's working fine for me.

**Comment by greyhwndz** [comment]
@philipwalton: checked it again. I misunderstood what you meant by 'sticky'. It's working great. Sorry for the false alarm
