### ISSUE TITLE
Width of individual Sizing seems to be incorrect

### ISSUE THREAD

**Issue by embats** [philipwalton/solved-by-flexbox#64]
I tried your demo but I have some issues with the individual sizing. On the grid page you provide an example with the headline »Individual Sizing«. There are three lines, with the following Columns:

1/2 | 1/2
auto | 1/3
1/4 | auto | 1/3

Since 1/3 is always 1/3 of the row, the 1/3 columns should be the same size, but they are not. Please see my Screenshot from Chrome Version 44.0.2403.157 (64-bit).

![bildschirmfoto 2015-08-27 um 08 45 06](https://cloud.githubusercontent.com/assets/1009797/9514244/be7525da-4c98-11e5-90eb-4b58fa4774d9.png)

**Comment by philipwalton** [comment]
What is that screen shot from? It doesn't look like it's from the site; when I look at that section on my demo site, it looks correct to me.

**Comment by KenPowers** [comment]
Looks good in these six browsers as well: https://www.browserstack.com/screenshots/17c62da1462db6347cb4c2625f70a507cdbcfc82

**Comment by embats** [comment]
Aye, I am an Idiot. The local sourcecode was modified, sorry.

**Comment by philipwalton** [comment]
No worries. Glad you figured it out.
