### ISSUE TITLE
basic responsiveness example?

### ISSUE THREAD

**Issue by TobyEalden** [philipwalton/solved-by-flexbox#65]
I'm probably missing something obvious, but I can't get responsiveness to work.

Based on the demo site, the following should reduce to a single column on resizing, but it doesn't appear to work for me...

```
<!doctype html>
<html>
<head>
<link rel="stylesheet" href="./grid.css" type="text/css" />
</head>
<body>
<div class="Grid Grid--gutters Grid-full large-Grid--fit">
	<div class="Grid-cell">
		one
	</div>
	<div class="Grid-cell">
		two
	</div>
	<div class="Grid-cell">
		three
	</div>
	<div class="Grid-cell">
		four
	</div>
</div>
</body>
</html>
```

**Comment by philipwalton** [comment]
You've written `Grid-full` but it should be `Grid--full` (two dashes). Check out the [SUIT CSS convention documentation](https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md) to see what the difference is.
