### ISSUE TITLE
Holy Grail Layout main content gets too big.

### ISSUE THREAD

**Issue by nextgenthemes** [philipwalton/solved-by-flexbox#68]
I have this issue in Firefox 41 Ubuntu 15.10 x64

See this screenshot at 769px width. Look of the right sidebar gets cut off.
![flexbux1](https://cloud.githubusercontent.com/assets/1780826/10254204/6e3b3c32-6942-11e5-92eb-c12028a70bcf.png)
Only fits screen as I go bigger.
![flexbux2](https://cloud.githubusercontent.com/assets/1780826/10254203/6e3abe60-6942-11e5-91d7-35a42109e348.png)

It seems to be caused my the content in the content container, if I delete anything the problem disappears.

Chromium not seems to have this problem. Is this I Firefox bug? Is there a workaround?

**Comment by philipwalton** [comment]
By default, flex items aren't supposed to shrink to smaller than their default minimum content size. It seems that Firefox considers the width of the items in the `<pre>` tags (code blocks) to be the minimum content size, enough though the `<pre>` tags themselves are set to `overflow: auto`. I think this is probably a Firefox bug, but I'm not 100% sure.

If you don't want this behavior, you can set `min-width: 0` on `HolyGrail-content`, and it'll allow the content area to shrink to as small as possible.

**Comment by nextgenthemes** [comment]
@philipwalton Thanks, you should include this fix in your code. In my quick test `overflow: auto;` on `HolyGrail-content` seems to have the same effect.

**Comment by Jip-Hop** [comment]
I'm seeing the same issue too in Chrome V64.0 on MacOS. So it's not a Firefox specific issue. Thanks @nextgenthemes for suggesting the `overflow: auto;` fix. But I can indeed confirm the `<pre>` tags are causing the issue.

![overflow](https://user-images.githubusercontent.com/2871973/37560329-62132b6a-2a36-11e8-8ae2-c101261ac5ea.jpg)
