### ISSUE TITLE
Not able to git clone from given git url

### ISSUE THREAD

**Issue by abhishekbhalani** [philipwalton/solved-by-flexbox#70]
I tried to make git clone to view locally but due to below fatal error..
![image](https://cloud.githubusercontent.com/assets/1845707/10862794/475ea5ac-7fdd-11e5-8ccd-8c2728227ff0.png)

**Comment by philipwalton** [comment]
Try cloning using HTTPS instead of SSH. In other words, try doing this:

```sh
git clone https://github.com/philipwalton/solved-by-flexbox.git
```

**Comment by abhishekbhalani** [comment]
@philipwalton It's works for me.
Thank you.
