### ISSUE TITLE
Sticky footer works incorrectly in Chrome

### ISSUE THREAD

**Issue by waynedd** [philipwalton/solved-by-flexbox#74]
Took the demo page of sticky footer http://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/, I found unwanted blank spaces under the footer. It looked like this:

![123](https://cloud.githubusercontent.com/assets/2526811/11612413/f44f5492-9c33-11e5-9402-5be77a660760.jpg)

This issue was observed in Chrome 47.0.2526.73 on Windows 10, and this page worked well in my Microsoft Edge and IE 11. So, is it a bug, or is it my Chrome's problem?

**Comment by ragzor** [comment]
Seems to be working fine on my end Chrome 47.0.2526.73 Osx, check your extensions.

**Comment by waynedd** [comment]
@ragzor Many thanks for your suggestion. It was my problem. I removed an extension of online bank and it works fine now.
