### ISSUE TITLE
Lost link

### ISSUE THREAD

**Issue by igoradamenko** [philipwalton/solved-by-flexbox#80]
Hello.

Thanks for your work. Examples are awesome.

I think you lost one link in article about [sticky footer](https://github.com/philipwalton/solved-by-flexbox/blob/master/demos/sticky-footer.md). Look at the first paragraph, at the words 'existing' and 'solutions'. I think there must be two links :)

**Comment by philipwalton** [comment]
Thanks, this should be fixed via 4f4ec1491d3279f9086a8133bd15d4bd2248e619.
