### ISSUE TITLE
Sticky footer and background-image on body

### ISSUE THREAD

**Issue by FrontDevs** [philipwalton/solved-by-flexbox#82]
He discovered such a thing , if the body has a height of 100 %, background image can not be done on the entire site , but only on the height of the window . The screenshots can be seen all what ya.Est what is the solution? Sorry for my angl.Spasibo for miraculous solutions flexbox
http://prntscr.com/aavhes
http://prntscr.com/aavj8g
http://prntscr.com/aavjhb

**Comment by philipwalton** [comment]
That's why I think `min-height` is ultimately a better solution, and why I listed that as the recommended solution in the demo. Using `height` is primarily for cross-browser compatibility.
