### ISSUE TITLE
Sticky footer needs html height 100%

### ISSUE THREAD

**Issue by cmmartti** [philipwalton/solved-by-flexbox#83]
I was testing this method on a fresh page, and it wasn't working for me. I finally figured out that the `html` element also needs a height of `100%` set, otherwise the `body` is not bounded by anything. So for this example to be complete, add this line:

    html {
        height: 100%;
    }

I realise that this might be something simple that most people already do, but it had me stuck for a few minutes.

**Comment by waldyrious** [comment]
Check out the discussions in #11, #12, #19, #28, #30, and #82.

**Comment by philipwalton** [comment]
Setting `height: 100%` on `<html>` is only needed if you're using percentages. It's not needed if you're using `100vh` on `<body>`.

The issues @waldyrious linked to should give you some more context.
