### ISSUE TITLE
NPM for Solved-by-flexbox

### ISSUE THREAD

**Issue by manavsehgal** [philipwalton/solved-by-flexbox#84]
+1 vote for adding NPM repo synced to GitHub source for Solved-by-flexbox, so we can easily reuse within our projects and stay updated with latest changes in this repo.

Solved-by-flexbox is awesome and the stars counter shows. Favoring ease of reusability, while this repo reuses Suit CSS and Normalize.css over npm, I could not find an easy way to import Solved-by-flexbox into my project so I could build on top of all this awesome work, yet stay updated whenever this repo is updated.

**Comment by philipwalton** [comment]
Solved by Flexbox is not a library, it's a demo site. The code on this site is not indented to be used in production.

Other people have taken ideas form this site and created libraries around of them. I recommend using one of those libraries.

**Comment by manavsehgal** [comment]
Makes sense. Can you suggest links to libraries created around demos from this site?

**Comment by philipwalton** [comment]
I can't suggest any because I haven't used them, but I know a few people have created libraries based on some of these demos because I've seen them over the years.

Googling quickly showed this: https://github.com/kristoferjoseph/flexboxgrid

I'm sure you can find others to if you look.
