### ISSUE TITLE
Image width=100%

### ISSUE THREAD

**Issue by jpeg729** [philipwalton/solved-by-flexbox#85]
If you try nesting a grid inside a flex layout, and you like responsive images (`width: 100%`), things get strange really fast.

In Chrome (v50.0.2661.102) the image gets 100% of the flex container's inner width, not 100% of its immediate parent's inner width.

The following fragment works fine on its own, but not when inside another flex container.

```html
<div class="Grid--1of2">
  <div class="Grid-cell">
    <div>
      <img src="//placehold.it/350" style="display:block; width:100%;"/>
    </div>
  </div>
  <div class="Grid-cell">
    <img src="//placehold.it/350" style="display:block; width:100%;"/>
  </div>
</div>
```
Even stranger... if I set `max-width: 30%;` on the Grid-cells, the images get sized down, but the grid cells still stack up vertically instead of sitting side-by-side.

Because of this I have been unable to use flexbox to make a decent layout with responsively sized images.

I am having much more success using css tables for my layouts, and flex for the grids. That said, I have yet to try using a Media block inside a grid cell.

**Comment by philipwalton** [comment]
I'm not entirely sure what question you're asking in this issue.

Also, keep in mind, the CSS on this site is not intended to be a CSS framework like Bootstrap and the like, it's just a demo.

**Comment by jpeg729** [comment]
I didn't formulate a question, but given that I didn't see any mention of possible issues  concerning responsive image sizing, I assumed you weren't aware of them.

Maybe you should add a mention of the issue somewhere.

I would also like to see comparisons with the css tables approach where that would be appropriate.
For example, the Holy Grail layout can be done with css tables too with far greater compatibility but reduced flexibility. Grids too, can be done with css tables, but without any wrapping as far as I can see.

**Comment by philipwalton** [comment]
There are a ton of things that flexbox can do that tables can't. The point of this site is not to just talk about flexbox, but specifically to showcase things that cannot be done with existing CSS features.

Re: images, I don't think there's a particular issue with responsive images and flexbox, and even if there were, this demo site wouldn't be the right place to mention it. If you think you've found a bug, you should report it with the offending browsers.

You might also check out the [flexbugs](https://github.com/philipwalton/flexbugs) repo that I maintain that explains how to deal with common flexbox issues.

**Comment by jpeg729** [comment]
I found an explanation. I guess it isn't a bug, its just not what I expected.

https://github.com/suitcss/components-arrange/blob/master/lib/arrange.css#L58
