### ISSUE TITLE
@custom-media

### ISSUE THREAD

**Issue by yochanan** [philipwalton/solved-by-flexbox#87]
Hi,
I cannot get the @custom-media variables to get recognized.
Here is my implementation:
http://104.131.86.28/
It works when @media queries set literal dimensions, like this:
@media (min-width: 768px)

**Comment by philipwalton** [comment]
`@custom-media` is not yet supported in all browsers. The Solved by Flexbox site uses [PostCSS](https://github.com/postcss/postcss) to process these into currently usable CSS.
