### ISSUE TITLE
add a chinese version

### ISSUE THREAD

**Issue by callmelanmao** [philipwalton/solved-by-flexbox#90]
hi there, i'm a developer from china, i like your project, it's great and flexbox is awesome. i have translated
this project into chinese, the project url is [solved-by-flexbox-cn](https://github.com/itechifree/solved-by-flexbox-cn), can you add a link to project in you README.md for people who is not good at english to read my chinese version.

thanks, happy day!

**Comment by xiaokaike** [comment]
good job

**Comment by philipwalton** [comment]
Added, thanks!
